---

- name: Replace sources.list
  become: true
  copy:
      src: 16.04.sources.list
      dest: /etc/apt/sources.list
      backup: yes
  tags:
      - apt


- name: Add Debug Symbol Repository
  become: true
  template:
      src: 16.04.ddebs.list
      dest: /etc/apt/sources.list.d/ddebs.list
  tags:
       - kernel_debug


- name: Add Debug Symbol Key
  become: true
  apt_key:
      url: http://ddebs.ubuntu.com/dbgsym-release-key.asc
      state: present
  tags:
      - kernel_debug


- name: Add the GPG key for the official Docker repository
  become: true
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  tags:
      - docker


- name: Add Docker Repository
  become: true
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
  tags:
      - docker


- name: Update & Upgrade & Install preset packages
  become: true
  apt:
      update_cache: yes
      #upgrade: yes
  tags:
      - apt
