---

- name: Replace sources.list
  become: true
  copy:
      src: 16.04.sources.list
      dest: /etc/apt/sources.list
      backup: yes
  tags:
      - apt
  notify:
      - apt_update


- name: Add Debug Symbol Repository
  become: true
  block:
      - template:
          src: 16.04.ddebs.list
          dest: /etc/apt/sources.list.d/ddebs.list
      - apt_key:
          url: http://ddebs.ubuntu.com/dbgsym-release-key.asc
          state: present
      - apt:
          update_cache: yes

  tags:
       - kernel_debug
       - debug


- name: Add Docker Repository
  become: true
  block:
      - apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
          state: present
      - apt:
          update_cache: yes
  tags:
      - docker
