---

- name: Replace sources.list
  become: true
  template:
      src: sources.list
      dest: /etc/apt/sources.list
      backup: yes
  tags:
      - apt
  notify:
      - apt_update


- name: Add debug symbol repository
  become: true
  block:
      - name: Add debug symbol sources
        template:
          src: ddebs.list
          dest: /etc/apt/sources.list.d/ddebs.list
      - name: Add dbgsym-key
        apt_key:
          url: http://ddebs.ubuntu.com/dbgsym-release-key.asc
          state: present
      - apt:
          update_cache: yes
  tags:
       - kernel_debug
       - debug


- name: Add docker repository
  become: true
  block:
      - name: Add key of docker repository
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - name: Add docker repository
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
          state: present
      - name: Update apt cache
        apt:
          update_cache: yes
  tags:
      - docker
