---

- name: Replace sources.list
  become: true
  copy:
      src: 16.04.sources.list
      dest: /etc/apt/sources.list
      backup: yes
  tags:
      - apt


- name: Add Debug Symbol Repository
  become: true
  template:
      src: 16.04.ddebs.list
      dest: /etc/apt/sources.list.d/ddebs.list
  tags:
       - kernel_debug


- name: Add Debug Symbol Key
  become: true
  apt_key:
      url: http://ddebs.ubuntu.com/dbgsym-release-key.asc
      state: present
  tags:
      - kernel_debug


- name: Add Docker Key
  become: true
  apt_key:
      keyserver: hkp://ha.pool.sks-keyservers.net:80
      keyring: adv
      id: 58118E89F3A912897C070ADBF76221572C52609D
      state: present
  tags:
      - docker


- name: Add Docker Repoitory
  become: true
  copy:
      src: 16.04.docker.list
      dest: /etc/apt/sources.list.d/docker.list
  tags:
      - docker


- name: Update & Upgrade & Install preset packages
  become: true
  apt:
      update_cache: yes
      #upgrade: yes
  tags:
      - apt
