---

- name: Install essential packages
  become: true
  apt:
      name: "{{ item }}"
      state: present
  with_items: "{{essential_packages}}"
  tags:
      - preset


- name: Configure essential essential packages
  block:
      - name: Configure tmux
        copy:
          src: .tmux.conf
          dest: ~/.tmux.conf
          backup: true
      - name: Configure pip directory
        file:
          path: ~/.pip
          state: directory
      - name: Configure pip mirrors
        copy:
          src: pip.conf
          dest: ~/.pip/pip.conf
      - name: Configure vim plugin repository
        git:
          repo: git://github.com/VundleVim/Vundle.vim.git
          dest: ~/.vim/bundle/Vundle.vim
      - name: Configure vim
        copy:
          src: .vimrc
          dest: ~/.vimrc
          backup: true
      - name: Install vim plugin
        shell: vim +PluginInstall +qall
  tags:
      - preset


- name: Install Oh-My-Zsh
  block:
      #- shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      - name: Download oh-my-zsh
        get_url:
          url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
          dest: /tmp/install-oh-my-zsh.sh
          mode: 0700
      - name: Install oh-my-zsh
        shell: sh -c /tmp/install-oh-my-zsh.sh
        ignore_errors: yes
      - debug:
          msg: "Change default shell: chsh -s /usr/bin/zsh"
      # - name: Change default shell to zsh
      #   shell: chsh -s /usr/bin/zsh
  #ignore_errors: yes
  tags:
      - preset
