---

- name: Install essential packages
  become: true
  apt:
      name: "{{ item }}"
      state: present
  with_items: "{{essential_packages}}"
  tags:
      - preset


- name: Configure essential essential packages
  block:
      - copy:
          src: .tmux.conf
          dest: ~/.tmux.conf
          backup: true
      - file:
          path: ~/.pip
          state: directory
      - copy:
          src: pip.conf
          dest: ~/.pip/pip.conf
      - git:
          repo: git://github.com/VundleVim/Vundle.vim.git
          dest: ~/.vim/bundle/Vundle.vim
      - copy:
          src: .vimrc
          dest: ~/.vimrc
          backup: true
      - shell: vim +PluginInstall +qall
  tags:
      - preset


- name: Install Oh-My-Zsh
  block:
      - shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      - shell: chsh -s /usr/bin/zsh
  ignore_errors: yes
  tags:
      - preset
