---

- name: Install essential packages
  become: true
  apt:
      name: "{{ item }}"
      state: present
  with_items: "{{essential_packages}}"
  tags:
      - preset


- name: Install docker
  become: true
  apt:
      name: docker-ce
      state: present
  tags:
      - docker


- name: Install Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  ignore_errors: yes
  tags:
      - preset


- name: Change the default shell
  shell: chsh -s /usr/bin/zsh
  tags:
      - preset


- name: Configurate tmux
  copy:
      src: .tmux.conf
      dest: ~/.tmux.conf
      backup: true
  tags:
      - preset


- name: Create pip directory
  file:
      path: ~/.pip
      state: directory
  tags:
      - preset


- name: Configurate pip
  copy:
      src: pip.conf
      dest: ~/.pip/pip.conf
  tags:
      - preset


- name: Clone Vundle, VIM plugin manager.
  git:
      repo: git://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim
  tags:
      - preset

- name: Copy vimrc
  copy:
      src: .vimrc
      dest: ~/.vimrc
      backup: true
  tags:
      - preset


- name: Install preset vim plugin
  shell: vim +PluginInstall +qall
  tags:
      - preset
