---

- name: Install Docker-CE and docker-compose
  become: true
  block:
      - name: Install docker-ce
        apt:
          name: docker-ce
          state: present
      - name: Append user into docker group
        user:
          name: "{{ ansible_user }}"
          groups: docker
          append: yes
      - name: Install docker-compose
        pip:
          name: docker-compose
          umask: "0022"
  tags:
      - docker
