---

- name: Install Docker-CE and docker-compose
  become: true
  block:
      - apt:
          name: docker-ce
          state: present
      - user:
          name: "{{ ansible_user }}"
          groups: docker
          append: yes
      - pip:
          name: docker-compose
          umask: 0022
  tags:
      - docker
